--- 
- hosts: all 
  become: yes
  tasks: 
        - name: i want to insatall apache
          apt:
              name: apache2
              sate: present 
              when: ansible_os_family --"Debian"  